name: Build Document
on: [push]
jobs:
  build_document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            sed -i "s/fontset=ubuntu/fontset=fandol/g" latex-talk.tex
            latexmk latex-talk
      - uses: actions/upload-artifact@v3
        with:
          name: talk-slides
          path: latex-talk.pdf
